services:
    container_name: krusader
    image: djaydev/krusader
    restart: unless-stopped
    privileged: true
    ports:
      - 5800:5800
      - 5900:5900
    environment:
      - PUID=<your_UID>
      - PGID=<your_GID>
      - TZ=<your_time_zone>
      - TEMP_FOLDER=<path_to_store_krusader_temp_files>
    volumes:
      - <path_to_store_config_files>:/config:rw
      - <path_to_your_root_dir>:/<wanted_dir>:rw
      - <path_to_your_home_dir>:/<wanted_dir>:rw
      - /etc/localtime:/etc/localtime:ro
      # optionnal this is to mount a disk or a share
      # you can add multiple share or disk
      - <path_to_your_share_or_mounted_disk>:/<wanted_dir>:rw
