services:
    image: linuxserver/openvpn-as
    container_name: openvpn-as
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=<your_uid>
      - PGID=<your_gid>
      - TZ=<your_time_zone>
      - INTERFACE=bridge #optional
    volumes:
      - <path_to_where_you_want_to_store_data>:/config
    ports:
      - 943:943
      - 9443:9443
      - 1194:1194/udp
    restart: unless-stopped
